### ISSUE TITLE
what is snapshot.cgi

### ISSUE THREAD

**Issue by navotera** [zyphlar/ip-camera-proxy#2]
hii.. what is snapshot.cgi file, what for is it ? where i can find it ?

i believe this code would not run if that file is not exist

thanK :)

**Comment by zyphlar** [comment]
snapshot.cgi is a file on the webcams I use which returns a JPEG image.
Many other webcams have a similar feature: just replace snapshot.cgi with
whatever your webcam uses (perhaps fullsize.jpg?camera=1 or maybe image.cgi)

**Comment by navotera** [comment]
thanks bro... and thanks for the great from u :+1:
